services:
  db:
    restart: "no"
    ports:
      - "3306:3306"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - "8000:8000"  # FastAPI/Uvicorn
      - "5000:5000"  # Flask web interface
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: true
