[project]
name = "vannasql-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "vanna[chromadb,mysql,ollama,postgres]>=0.7.9",
]
